#!/bin/sh

#
# Start the CompressorCam service....
#

cd /home/pi/ccam

case "$1" in
  start)
    printf "Starting CompressorCam: "
    python3 ccam.py & 
    [ $? = 0 ] && echo "OK" || echo "FAIL"
    ;;
  stop)
    printf "Stopping CompressorCam: "
    # TODO...
    [ $? = 0 ] && echo "OK" || echo "FAIL"
    ;;
  restart|reload)
    "$0" stop
    "$0" start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
esac

exit $?
